Correction vecteur
infra-geo-ouverte/igo pull request #191
Opened 2016-11-22 18:52 UTC by mikesmichael

Corrections mineures dans la classe Vecteur (variable déclarée sans var devient globale, e.occurence dans _selection est un array d'occurences plutôt qu'un objet occurence

2016-11-22 19:34 UTC, mbarbeau requested changes

2016-11-22 19:34 UTC, mbarbeau commented on interfaces/navigateur/public/js/app/couche/protocole/vecteur.js
> +        var tousLesStyles = typeof tousLesStyles === "undefined"?undefined:tousLesStyles;
La variable n'est pas globale puisqu'elle est déclarée implicitement dans le paramètre de la fonction.
Par contre, je ne vois pas l'intérêt de cette ligne...
Je crois qu'on peut la supprimer.

2016-11-24 21:59 UTC, mbarbeau approved these changes

2016-11-25 15:11 UTC, mbarbeau commented on interfaces/navigateur/public/js/app/couche/protocole/vecteur.js
> -        if (that._.obtenirId() !== e.occurence.vecteur.obtenirId()){return false};
De mon côté et selon le code, c'est bien une occurence et non un array. Est-ce que tu as un cas particulier qui retourne un array?

2016-11-25 15:19 UTC, mbarbeau commented on interfaces/navigateur/public/js/app/couche/protocole/vecteur.js
> +            $('#'+this._layer.arborescence.id).find("image").css({"height":"15","width":"15","x":"0","y":"0"});
Il a déjà un bout de code qui redimension l'image dans l'arborescence. La hauteur maximum est de 20 pixel et il garde la proportion entre hauteur et largeur. Voir la function createRuleRenderer de VectorLegend.js dans GeoExt.

2016-11-25 15:21 UTC, mbarbeau requested changes

2016-11-25 15:21 UTC, mbarbeau commented on interfaces/navigateur/public/js/app/couche/protocole/vecteur.js
> +        $.each(e.occurence, function(ind, occu) {
De mon côté et selon le code, c'est bien une occurence et non un array. Est-ce que tu as un cas particulier qui retourne un array?

2016-11-25 15:22 UTC, mbarbeau requested changes

2016-11-25 15:22 UTC, mbarbeau commented on interfaces/navigateur/public/js/app/couche/protocole/vecteur.js
> +            $('#'+this._layer.arborescence.id).find("image").css({"height":"15","width":"15","x":"0","y":"0"});
Il a déjà un bout de code qui redimension l'image dans l'arborescence. La hauteur maximum est de 20 pixel et il garde la proportion entre hauteur et largeur. Voir la function createRuleRenderer de VectorLegend.js dans GeoExt.

2016-11-28 15:53 UTC, mikesmichael reviewed
Correction suite au commentaire dans _selection

2016-11-28 15:53 UTC, mikesmichael commented on interfaces/navigateur/public/js/app/couche/protocole/vecteur.js
> +        var tousLesStyles = typeof tousLesStyles === "undefined"?undefined:tousLesStyles;
Tu as raison, j'ai regardé trop vite, c'est parce qu'il y a _var_ pour la ligne 519 avec un nom différent

2016-11-28 15:53 UTC, mikesmichael commented on interfaces/navigateur/public/js/app/couche/protocole/vecteur.js
> +        $.each(e.occurence, function(ind, occu) {
En effet, j'ai fait la correction pour que l'outil du panneauTable fonctionne mais ça brisé le reste. J'ai fait une correction pour gérer les 2 cas. C'est l'outil Sélection/Afficher la sélection seulement qui utilise un array d'occurences.

2016-11-28 16:04 UTC, mikesmichael commented on interfaces/navigateur/public/js/app/couche/protocole/vecteur.js
> +            $('#'+this._layer.arborescence.id).find("image").css({"height":"15","width":"15","x":"0","y":"0"});
Sais-tu comment l'appliquer?, D'après ce que je vois, il faut passer un paramètre rule. je ne suis pas très familier avec les object rule d'Openlayers, je viens de regarder la classe et je ne crois pas pouvoir faire ça rapidement. Aurais-tu le temps de regarder ça? Si tu ne peux pas, je prendrai connaissance de ça losque j'aurai un peu plus de temps.

2016-11-28 18:54 UTC, mbarbeau commented on interfaces/navigateur/public/js/app/couche/protocole/vecteur.js
> +            $('#'+this._layer.arborescence.id).find("image").css({"height":"15","width":"15","x":"0","y":"0"});
Chaque style que tu appliques crée un rule d'Openlayers. Donc si tu utilises une image (icone) pour le style, il devrait passer par la redimension de l'image. 

Normalement, il devrait être appliqué par défaut. Faudrait comprendre pourquoi dans ton cas, la redimension n'est pas faite.

2016-11-28 19:13 UTC, mikesmichael commented on interfaces/navigateur/public/js/app/couche/protocole/vecteur.js
> +            $('#'+this._layer.arborescence.id).find("image").css({"height":"15","width":"15","x":"0","y":"0"});
C'est dans le panneauEdition du module Edition que j'utilise ça, 

Y vois-tu un problème dans la définition? Le style.icone a une valeur comme celle-ci: "/igo/interfaces/ModuleExterne/FADQ/image/Carre_grain.png"

`var filtres = new Array();`
```
if(style.icone !== undefined && style.icone != "" && style.icone != null)
            {
               var obj = {titre: style.title, 
                       filtre: '['+that.styleGeometrieFiltre+'] == \''+style.code+'\'',
                       style: { icone: style.icone,
                              opacite: 1,
                              iconeHauteur:40,
                              iconeLargeur:40,
                              etiquetteLimiteEpaisseur:2,
                              etiquetteOffsetY: -2,
                              etiquetteLimiteCouleur:"#EBEBEB",
                              index: 999999
                       }
                };
                    
            }
```

...
```
  filtres.push(obj);
styleCourant.ajouterFiltres(filtres); 
```

2016-11-28 20:48 UTC, mbarbeau commented on interfaces/navigateur/public/js/app/couche/protocole/vecteur.js
> +            $('#'+this._layer.arborescence.id).find("image").css({"height":"15","width":"15","x":"0","y":"0"});
Ça me semble bien beau...faudrait investiguer

2021-09-29 13:21 UTC, pelord commented
Archivage du dépot. Fermeture des issues/Pull requests

2021-09-29 13:21 UTC, closed without merging